Models/Actor.cs
using FileKeyReference;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MDB.Models
{
    public class Actor
    {
        public int Id { get; set; }
        [Required]
        [Display(Name = "Nom")]
        public string Name { get; set; }
        [Display(Name = "Date de naissance"), Required(ErrorMessage = "La date de naissance est requise")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Nationalité")]
        public string CountryCode { get; set; }
        [Display(Name = "Avatar")]
        public string AvatarImageKey { get; set; } = "";
        #region Avatar management
        [JsonIgnore]
        private static ImageFileKeyReference AvatarsRepository = new ImageFileKeyReference(@"/Images_Data/Actor_Avatars/", @"no_avatar.png");
        [JsonIgnore]
        public string AvatarImageData { get; set; }
        public string GetAvatarURL(bool thumbailFormat = false)
        {
            return AvatarsRepository.GetURL(AvatarImageKey, thumbailFormat);
        }
        public void SaveAvatar()
        {
            AvatarImageKey = AvatarsRepository.Save(AvatarImageData, AvatarImageKey);
        }
        public void RemoveAvatar()
        {
            AvatarsRepository.Remove(AvatarImageKey);
        }
        #endregion

        [JsonIgnore]
        public List<Casting> Castings { get { return DB.Castings.ToList().Where(c => c.ActorId == Id).ToList(); } }
        [JsonIgnore]
        public List<Movie> Movies
        {
            get
            {
                List<Movie> movies = new List<Movie>();
                foreach (var casting in Castings)
                    movies.Add(casting.Movie);
                return movies.OrderBy(c => c.Title).ToList();
            }
        }
        public void DeleteCastings()
        {
            foreach (var casting in Castings)
                DB.Castings.Delete(casting.Id);
        }
        public bool UpdateCastings(List<int> moviesId)
        {
            DeleteCastings();
            if (moviesId != null)
                foreach (var movieId in moviesId)
                    DB.Castings.Add(new Casting { ActorId = Id, MovieId = movieId });
            return true;
        }
       
    }
}

Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MDB.Models;

namespace MDB.Controllers
{
    public class ActorsController : Controller
    {
        [OnlineUsers.UserAccess]
        public ActionResult Index()
        {
            return View();
        }
        [OnlineUsers.UserAccess(false/* do not reset timeout*/)]
        public ActionResult Actors(bool forceRefresh = false)
        {
            if (forceRefresh || DB.Actors.HasChanged)
            {
                return PartialView(DB.Actors.ToList().OrderBy(c => c.Name));
            }
            return null;
        }
        [OnlineUsers.PowerUserAccess]
        public ActionResult Create()
        {
            ViewBag.Castings = null;
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList(), "Title");
            return View(new Actor());
        }
        [OnlineUsers.PowerUserAccess]
        [HttpPost]
        public ActionResult Create(Actor actor, List<int> SelectedMoviesId)
        {
            if (ModelState.IsValid)
            {
                DB.Actors.Add(actor, SelectedMoviesId);
                return RedirectToAction("Index");
            }
            ViewBag.Castings = SelectListUtilities<Movie>.Convert(actor.Movies, "Title");
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList(), "Title");
            return View();
        }
        [OnlineUsers.UserAccess]
        public ActionResult Details(int id)
        {
            Actor actor = DB.Actors.Get(id);
            if (actor != null)
            {
                return View(actor);
            }
            return RedirectToAction("Index");
        }
        [OnlineUsers.PowerUserAccess]
        public ActionResult Edit(int id)
        {
            Actor actor = DB.Actors.Get(id);
            if (actor != null)
            {
                ViewBag.Castings = SelectListUtilities<Movie>.Convert(actor.Movies, "Title");
                ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList(), "Title");
                return View(actor);
            }
            return RedirectToAction("Index");
        }
        [OnlineUsers.PowerUserAccess]
        [HttpPost]
        public ActionResult Edit(Actor actor, List<int> SelectedMoviesId)
        {
            if (ModelState.IsValid)
            {
                DB.Actors.Update(actor, SelectedMoviesId);
                return RedirectToAction("Details", new {id = actor.Id });
            }
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(actor.Movies, "Title");
            ViewBag.Movies = SelectListUtilities<Movie>.Convert(DB.Movies.ToList(), "Title");
            return View(actor);
        }
        [OnlineUsers.PowerUserAccess]
        public ActionResult Delete(int id)
        {
            DB.Actors.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

Views/Actors/ActorForm.cshtml
@model MDB.Models.Actor
@{
    string pageTitle = Model.Id == 0 ? "Ajout d'acteur" : "Modification d'acteur";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3>@pageTitle</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.AvatarImageKey)

        <div class="form-group">
            @Html.Label("Nom", htmlAttributes: new { @class = "control-label col-md-2 legend" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2 legend" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control datepicker" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CountryCode, htmlAttributes: new { @class = "control-label col-md-2 legend" })
            <div class="col-md-10">
                @Helper.CountrySelector("CountryCode", Model.CountryCode)
                @Html.ValidationMessageFor(model => model.CountryCode, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.AvatarImageKey, htmlAttributes: new { @class = "control-label col-md-2 legend" })
            <div class="col-md-10">
                @Helper.ImageUploader(Model.Id, "AvatarImageData", Model.GetAvatarURL(), "~/Images_Data/Loading_icon.gif", "Cliquez pour choisir une image")
                @Html.ValidationMessageFor(model => model.AvatarImageData, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Filmographie", htmlAttributes: new { @class = "control-label col-md-2 legend" })
            <div class="col-md-10">
                @Helper.SelectionLists("SelectedMoviesId", ViewBag.Castings, ViewBag.Movies, 8)
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour", "Index")
</div>

Views/Actors/Actors.cshtml
@model IEnumerable<MDB.Models.Actor>

@foreach (var item in Model)
{
    <a href="@Url.Action("Details","Actors", new {id=item.Id})">
        <div class="ActorContainer">
            @Helper.Image(item.GetAvatarURL(true), "smallAvatar")
            <div class="ellipsis" style="margin-top:5px;text-align:center; width:inherit">@item.Name</div>
        </div>
    </a>
}

Views/Actors/Create.cshtml
@model MDB.Models.Actor

@{
    ViewBag.Title = "Create";
}

@{ Html.RenderPartial("ActorForm"); }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Actors/Details.cshtml
@model MDB.Models.Actor

@{
    ViewBag.Title = "Details " + Model.Name;
}
<div class="mainDetails">
    <div class="prevent-select" style="padding-top:10px;">
        <div style="display:grid; grid-template-columns:auto 35px 35px; align-items:baseline;">
            <div class="ActorDetailsName"> @Model.Name</div>
            @if ((bool)Session["CRUD_Access"])
            {
                @Helper.IconCmd("Actors", "Edit/" + Model.Id, "fa-edit", "Modifier...")
                @Helper.IconConfirmCmd("Actors", "Delete/" + Model.Id, "fa-times-rectangle-o", "Effacer " + Model.Name + "?")
            }
        </div>
        <div class="ActorDetails-left">
            <div>
                @Helper.Image(Model.GetAvatarURL(false), "largeAvatar")
                <div style="display: grid; grid-template-columns: 45px auto; margin-left:1px; margin-top: 8px; margin-bottom: 8px;align-items:center">
                    @Helper.CountryFlag(Model.CountryCode)
                    <div> Né le @Model.BirthDate.ToLongDateString()</div>

                </div>
            </div>
            <div class="ActorDetails-right">
                <div class="detailsSectionTitle">Filmographie</div>
                <div class="MoviesContainer" style="margin-top:10px">
                    @{ Html.RenderPartial("~/Views/Movies/Movies.cshtml", Model.Movies); }
                </div>
            </div>
        </div>
        <p>
            @Html.ActionLink("retour", "Index")
        </p>
    </div>
</div>

Views/Actors/Edit.cshtml
@model MDB.Models.Actor

@{
    ViewBag.Title = "Edit";
}

@{ Html.RenderPartial("ActorForm"); }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Actors/Index.cshtml
@model IEnumerable<MDB.Models.Actor>
@{
    ViewBag.Title = "Index";
}
<div class="prevent-select">
    <h2>
        Acteurs
        @if ((bool)Session["CRUD_Access"])
        {
            @Helper.IconCmd("Actors", "Create", "fa-plus-square", "Ajouter...")
        }
    </h2>

    <hr />
    <div class="main">
        <div id="ActorsContainer" class="ActorsContainer"> <!-- Refreshed periodically --> </div>
    </div>
</div>
@section Scripts {
    <script defer>
        let actors = new PartialRefresh("@Url.Action("Actors", "Actors")", "ActorsContainer", 5);
    </script>
}